version: '3.8'
services:
  server:
    environment:
      - DEBUG=*
    env_file:
      - .env.prod
    build: .
    container_name: workout-app
    ports:
      - '5000:5000'
    volumes:
      - .:/app